# Generated by Django 3.1.7 on 2021-05-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userpermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
