# Generated by Django 3.1.7 on 2021-06-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userpermissions_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
