# Generated by Django 3.1.7 on 2021-06-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_review_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingadress',
            name='shippingPrice',
        ),
        migrations.AddField(
            model_name='order',
            name='refundRequsted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
